apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-06-30T16:01:25Z"
  generation: 1
  labels:
    app: logger
  name: logger
  namespace: default
  resourceVersion: "1649"
  uid: 13e25e3b-8c83-425e-a058-3945a4fab752
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: logger
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logger
    spec:
      containers:
      - image: ubuntu/mysql
        imagePullPolicy: Always
        name: mysql
        command:
           - /usr/local/bin/hello
        volumeMounts:
        - name: bins
          mountPath: /usr/local/bin
      volumes:
      - name: bins
        configMap:
          name: bins
          defaultMode: 0777